version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Base CircleCI image
    steps:
      - checkout  # Pull latest code from repo
      - setup_remote_docker  # Enable Docker-in-Docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/djangoecom:latestcircleci .
            docker tag $DOCKERHUB_USERNAME/djangoecom:latestcircleci $DOCKERHUB_USERNAME/djangoecom:$CIRCLE_BUILD_NUM
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/djangoecom:$CIRCLE_BUILD_NUM
            docker push $DOCKERHUB_USERNAME/djangoecom:latestcircleci          
       
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
