version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Base CircleCI image
    steps:
      - checkout  # Pull latest code from repo
      
      - setup_remote_docker  # Enable Docker-in-Docker
      - persist_to_workspace:
          root: /tmp
          paths:
            - .
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/djangoecom:latest .

  push:
    docker:
      - image: cimg/base:stable  # Base CircleCI image
    steps:  
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/djangoecom:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - push:
          requires:
            - build
